
import { Item, ItemStatus } from './types';

export const INITIAL_ITEMS: Item[] = [
  {
    id: '1',
    name: 'Vintage Leather Wallet',
    description: 'A brown leather wallet with a worn look. Contains a university ID for "Alex Ray". Last seen near the library coffee shop.',
    location: 'Central Library',
    date: '2024-07-15T10:30:00Z',
    status: ItemStatus.Lost,
    contactInfo: 'alex.ray@university.edu',
    imageUrl: 'https://picsum.photos/seed/wallet/400/300',
    userId: 'alex.ray@university.edu',
  },
  {
    id: '2',
    name: 'Set of Keys on a Blue Lanyard',
    description: 'A set of three keys (one car key, two house keys) on a bright blue lanyard with a "Starlight Corp" logo. Found on a park bench.',
    location: 'City Park - East Entrance',
    date: '2024-07-16T15:00:00Z',
    status: ItemStatus.Found,
    contactInfo: 'finder-grace@email.com',
    imageUrl: 'https://picsum.photos/seed/keys/400/300',
    userId: 'finder-grace@email.com',
  },
  {
    id: '3',
    name: 'Black Framed Glasses',
    description: 'A pair of black, thick-framed prescription glasses in a soft grey case. Left behind in lecture hall 3B.',
    location: 'Main Campus - Lecture Hall 3B',
    date: '2024-07-14T13:00:00Z',
    status: ItemStatus.Lost,
    contactInfo: 'sam.jones@email.com',
    imageUrl: 'https://picsum.photos/seed/glasses/400/300',
    userId: 'sam.jones@email.com',
  },
  {
    id: '4',
    name: 'Red Umbrella',
    description: 'A large, bright red umbrella with a wooden handle. Found near the downtown bus stop. It is in good condition.',
    location: 'Downtown Bus Stop (Maple Ave)',
    date: '2024-07-17T08:45:00Z',
    status: ItemStatus.Found,
    contactInfo: 'bus-depot-lostfound@city.gov',
    imageUrl: 'https://picsum.photos/seed/umbrella/400/300',
    userId: 'bus-depot-lostfound@city.gov',
  },
   {
    id: '5',
    name: 'Airpods Pro Case',
    description: 'White Airpods Pro charging case (empty, no earbuds inside). Has a small scratch on the front. I think I dropped it on my way to the gym.',
    location: 'Sidewalk near "FitLife" Gym',
    date: '2024-07-18T18:00:00Z',
    status: ItemStatus.Lost,
    contactInfo: 'casey.b@email.com',
    imageUrl: 'https://picsum.photos/seed/airpods/400/300',
    userId: 'casey.b@email.com',
  },
  {
    id: '6',
    name: 'Scifi Novel: "Hyperion"',
    description: 'A paperback copy of the book "Hyperion" by Dan Simmons. Has some notes in the margins in the first few chapters. Found on the 5:30 PM train.',
    location: 'Metro Line 2, heading north',
    date: '2024-07-18T17:45:00Z',
    status: ItemStatus.Found,
    contactInfo: 'metro-lost-found@transpo.com',
    imageUrl: 'https://picsum.photos/seed/book/400/300',
    userId: 'metro-lost-found@transpo.com',
  },
];